from datetime import date, datetime
from typing import List, Any, AsyncGenerator
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, and_
from collections import defaultdict

from app.models.models import Student, Attendance, SchoolSettings, Class, Section, Subject

async def generate_register_stream(
    db: AsyncSession,
    class_id: int,
    section_id: int,
    subject_id: int,
    start_date: date,
    end_date: date,
    generated_by: str
) -> AsyncGenerator[List[Any], None]:
    """
    Yields rows of the Attendance Register matrix incrementally.
    This prevents loading a large formatted dataset entirely into memory.
    """
    # 1. Fetch academic details
    class_obj = await db.get(Class, class_id)
    section_obj = await db.get(Section, section_id)
    subject_obj = await db.get(Subject, subject_id)
    
    class_name = class_obj.name if class_obj else f"Class #{class_id}"
    section_name = section_obj.name if section_obj else f"Section #{section_id}"
    subject_name = subject_obj.name if subject_obj else f"Subject #{subject_id}"

    # 2. Fetch Institution settings
    settings_res = await db.execute(select(SchoolSettings).limit(1))
    settings = settings_res.scalar_one_or_none()
    institution_name = settings.school_name if settings else "AttendX Institution"

    # 3. Calculate Academic Year (June to May heuristic)
    if start_date.month >= 6:
        academic_year = f"{start_date.year}-{start_date.year + 1}"
    else:
        academic_year = f"{start_date.year - 1}-{start_date.year}"

    # 4. Fetch unique dates with attendance for this subject/section (non-N+1)
    dates_query = select(Attendance.date).join(Student, Attendance.student_id == Student.id).where(
        and_(
            Student.class_id == class_id,
            Student.section_id == section_id,
            Attendance.subject_id == subject_id,
            Attendance.date >= start_date,
            Attendance.date <= end_date
        )
    ).distinct().order_by(Attendance.date)
    dates_res = await db.execute(dates_query)
    unique_dates = [d[0] for d in dates_res.all()]

    # Yield metadata headers
    yield ["ACCREDITATION COMPLIANCE REPORT - NBA COURSE-WISE ATTENDANCE REGISTER"]
    yield ["Institution Name:", institution_name]
    yield ["Academic Year:", academic_year]
    yield ["Subject Name:", subject_name]
    yield ["Class & Section:", f"{class_name} - {section_name}"]
    yield ["Date Range:", f"{start_date.isoformat()} to {end_date.isoformat()}"]
    yield ["Generated By:", generated_by]
    yield ["Generated On:", datetime.now().strftime("%Y-%m-%d %H:%M:%S")]
    yield [] # empty separator line

    if not unique_dates:
        yield ["No records found for selected criteria."]
        return

    # 5. Fetch Students sorted by Roll Number
    students_res = await db.execute(
        select(Student).where(
            and_(Student.class_id == class_id, Student.section_id == section_id)
        ).order_by(Student.register_number)
    )
    students = students_res.scalars().all()
    
    if not students:
        yield ["No students found for this class/section."]
        return

    # 6. Fetch Attendance records for all these students in one query (non-N+1)
    student_ids = [s.id for s in students]
    att_res = await db.execute(
        select(Attendance).where(
            and_(
                Attendance.student_id.in_(student_ids),
                Attendance.subject_id == subject_id,
                Attendance.date >= start_date,
                Attendance.date <= end_date
            )
        )
    )
    attendances = att_res.scalars().all()

    # Map student_id -> date -> status character (P/A/L)
    att_map = defaultdict(dict)
    for att in attendances:
        status_str = getattr(att.status, 'value', str(att.status))
        val = 'P' if status_str == 'present' else 'A' if status_str == 'absent' else 'L' if status_str == 'on_leave' else '-'
        att_map[att.student_id][att.date] = val

    # 7. Yield headers
    formatted_dates = [d.strftime("%d-%b") for d in unique_dates]
    headers = ["Roll Number", "Student Name"] + formatted_dates + ["Attendance %"]
    yield headers

    # 8. Yield student records incrementally
    for student in students:
        s_att = att_map[student.id]
        row_statuses = []
        
        present = 0
        absent = 0
        
        for d in unique_dates:
            status_char = s_att.get(d, '-')
            row_statuses.append(status_char)
            if status_char == 'P':
                present += 1
            elif status_char == 'A':
                absent += 1
                
        effective = present + absent
        pct = round((present / effective * 100), 2) if effective > 0 else 100.0 if present > 0 else 0.0
        
        row = [student.register_number, student.name] + row_statuses + [f"{pct}%"]
        yield row
