from datetime import date, datetime
from typing import List, Dict, Any, Tuple
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, and_

from app.models.models import AuditLog, Teacher, SchoolSettings

async def generate_audit_trail_dataset(
    db: AsyncSession,
    start_date: date,
    end_date: date,
    generated_by: str
) -> Tuple[List[str], List[List[Any]], Dict[str, Any]]:
    """
    Business logic to compile the Audit Trail compliance report.
    Returns: (headers, rows, summary_info)
    """
    # 1. Fetch Institution settings
    settings_res = await db.execute(select(SchoolSettings).limit(1))
    settings = settings_res.scalar_one_or_none()
    institution_name = settings.school_name if settings else "AttendX Institution"

    # 2. Calculate Academic Year (June to May heuristic)
    if start_date.month >= 6:
        academic_year = f"{start_date.year}-{start_date.year + 1}"
    else:
        academic_year = f"{start_date.year - 1}-{start_date.year}"

    # 3. Combine dates with time to capture full day logs
    start_datetime = datetime.combine(start_date, datetime.min.time())
    end_datetime = datetime.combine(end_date, datetime.max.time())

    # 4. Fetch AuditLogs with outerjoin on Teacher to avoid N+1 queries
    query = (
        select(AuditLog, Teacher.name, Teacher.role)
        .outerjoin(Teacher, AuditLog.performed_by == Teacher.id)
        .where(
            and_(
                AuditLog.timestamp >= start_datetime,
                AuditLog.timestamp <= end_datetime
            )
        )
        .order_by(AuditLog.timestamp.desc())
    )
    result = await db.execute(query)
    records = result.all()

    rows = []
    
    # 5. Formulate rows
    for log, user_name, user_role in records:
        # Resolve details from metadata or construct a description
        details = ""
        if log.metadata_ and isinstance(log.metadata_, dict):
            details = log.metadata_.get("details", "")
            if not details:
                # If there are metadata keys, format them
                meta_items = [f"{k}={v}" for k, v in log.metadata_.items() if k != "details"]
                if meta_items:
                    details = f"{log.action} metadata: {', '.join(meta_items)}"
        
        if not details:
            details = f"{log.action} performed on {log.entity_type} ({log.entity_name})"

        rows.append([
            log.timestamp.strftime("%Y-%m-%d %H:%M:%S"),
            user_name or f"User #{log.performed_by}",
            (user_role or "system").capitalize(),
            log.action,
            log.entity_type,
            details
        ])

    summary_info = {
        "total_records": len(records),
        "institution_name": institution_name,
        "academic_year": academic_year,
        "date_range": f"{start_date.isoformat()} to {end_date.isoformat()}",
        "generated_by": generated_by,
        "generated_on": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

    headers = ["Timestamp", "User", "Role", "Action", "Entity", "Details"]

    return headers, rows, summary_info

def format_audit_trail_csv(headers: List[str], rows: List[List[Any]], summary: Dict[str, Any]) -> List[List[Any]]:
    """
    Formats the audit trail with Compliance Metadata Headers.
    """
    formatted_rows = [
        ["ACCREDITATION COMPLIANCE REPORT - DATA INTEGRITY & AUDIT TRAIL"],
        ["Institution Name:", summary["institution_name"]],
        ["Academic Year:", summary["academic_year"]],
        ["Date Range:", summary["date_range"]],
        ["Generated By:", summary["generated_by"]],
        ["Generated On:", summary["generated_on"]],
        [], # empty separator line
        headers
    ]
    
    formatted_rows.extend(rows)
    return formatted_rows
